#!/usr/bin/env python3
"""refresh_state.py — refresh ONLY the <!-- auto:start -->..<!-- auto:end --> block of
STATE.md from git + the docs vault. Idempotent; manual (run via /reflect), NEVER a hook
(so it never leaves an uncommitted file lying around between commits)."""
from __future__ import annotations
import subprocess, datetime, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS, STATE = ROOT / "docs", ROOT / "STATE.md"

def git(*a: str) -> str:
    return subprocess.run(["git", "-C", str(ROOT), *a], capture_output=True, text=True).stdout.strip()

def count(sub: str) -> int:
    d = DOCS / sub
    return len([p for p in d.glob("*.md") if p.name.lower() != "readme.md"]) if d.is_dir() else 0

def latest_title(sub: str) -> str:
    d = DOCS / sub
    files = sorted((p for p in d.glob("*.md") if p.name.lower() != "readme.md"),
                   key=lambda p: p.name, reverse=True) if d.is_dir() else []
    if not files:
        return "—"
    for line in files[0].read_text(errors="ignore").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return files[0].stem

now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
block = (
    "<!-- auto:start -->\n"
    "<!-- generated by tools/refresh_state.py — do not edit by hand -->\n"
    f"- **Refreshed:** {now}\n"
    f"- **Branch:** `{git('rev-parse','--abbrev-ref','HEAD')}`\n"
    f"- **Latest commit:** `{git('rev-parse','--short','HEAD')}` — "
    f"{git('log','-1','--pretty=%s')} ({git('log','-1','--pretty=%cs')})\n"
    f"- **Docs:** {count('decisions')} decisions · {count('features')} features · "
    f"{count('sessions')} sessions · {count('learnings')} learnings\n"
    f"- **Latest decision:** {latest_title('decisions')}\n"
    f"- **Latest session:** {latest_title('sessions')}\n"
    "<!-- auto:end -->"
)
if not STATE.is_file():
    print("ERROR: STATE.md not found at repo root", file=sys.stderr); sys.exit(1)
txt = STATE.read_text()
if "<!-- auto:start -->" not in txt:
    print("ERROR: STATE.md missing <!-- auto:start --> markers", file=sys.stderr); sys.exit(1)
STATE.write_text(re.sub(r"<!-- auto:start -->.*?<!-- auto:end -->", block, txt, flags=re.S))
print(f"STATE.md auto-block refreshed @ {now}")
